language: java

notifications:
  email:
    recipients:
      - google-java-format-dev+travis@google.com
    on_success: change
    on_failure: always

jdk:
  - oraclejdk7
  - oraclejdk8

# use travis-ci docker based infrastructure
sudo: false

cache:
  directories:
    - $HOME/.m2
