language: java

notifications:
  email:
    recipients:
      - google-java-format-dev+travis@google.com
    on_success: change
    on_failure: always

jdk:
  - oraclejdk7
  - oraclejdk8

# use travis-ci docker based infrastructure
sudo: false

cache:
  directories:
    - $HOME/.m2

install: mvn -pl '!idea_plugin' install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn -pl '!idea_plugin' test -B
